### ISSUE TITLE
Missing Information For:tumblr.com

### ISSUE THREAD

**Issue by maya1612** [xorprojects/We-LGBT#19]
- Name: Maya
- Description: I personally say that tumblr is one of the most open social media websites currently available to LGBT+ youth and adults. Though, people can be judgmental, the majority of tumblr users are part of the LGBT+ community, so I personally think that tumblr definitely supports the community (if not itself, through it's users).

**Comment by crutchcorn** [comment]
We're trying to rate the company themselves, not consumers or users. :) Any references to what they have done?

**Comment by danielhickman** [comment]
True, but I think Tumblr has continued support because of it's users. Here's a [post from the Tumblr staff](https://staff.tumblr.com/post/145260555185/here-you-go-tumblr-a-little-burst-of-pride-for) from just this year. I couldn't find what Tumblr did for June 26, 2015 but I have a feeling they did something.
